/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_szakacs_kpi_fei_tuke_game_player_PlayerNativeA */

#ifndef _Included_com_szakacs_kpi_fei_tuke_game_player_PlayerNativeA
#define _Included_com_szakacs_kpi_fei_tuke_game_player_PlayerNativeA
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_szakacs_kpi_fei_tuke_game_player_PlayerNativeA
 * Method:    act
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_szakacs_kpi_fei_tuke_game_player_PlayerNativeA_act
  (JNIEnv *, jobject);

/*
 * Class:     com_szakacs_kpi_fei_tuke_game_player_PlayerNativeA
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_szakacs_kpi_fei_tuke_game_player_PlayerNativeA_initialize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
