/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_szakacs_kpi_fei_tuke_game_player_PlayerNativeA */

#ifndef _Included_com_szakacs_kpi_fei_tuke_game_player_PlayerNativeA
#define _Included_com_szakacs_kpi_fei_tuke_game_player_PlayerNativeA
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_szakacs_kpi_fei_tuke_game_player_PlayerNativeA
 * Method:    initializeNativeCode
 * Signature: (Lcom/szakacs/kpi/fei/tuke/game/intrfc/proxies/PlayerGameInterface;)V
 */
JNIEXPORT void JNICALL Java_com_szakacs_kpi_fei_tuke_game_player_PlayerNativeA_initializeNativeCode
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_szakacs_kpi_fei_tuke_game_player_PlayerNativeA
 * Method:    act
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_szakacs_kpi_fei_tuke_game_player_PlayerNativeA_act
  (JNIEnv *, jobject);

/*
 * Class:     com_szakacs_kpi_fei_tuke_game_player_PlayerNativeA
 * Method:    deallocate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_szakacs_kpi_fei_tuke_game_player_PlayerNativeA_deallocate
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
